<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>qvs</string>
	</array>
	<key>name</key>
	<string>QlikView</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#scriptStatements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numerics</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rangeFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#stringFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dateTimeFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#colorFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interRecordFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#counterFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#aggregationFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#systemFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logicalFunctions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#macros</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#fieldNames</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;|\+|\\|&lt;|&lt;=|&gt;|&gt;=|\/|,|;|=</string>
			<key>name</key>
			<string>keyword.operator.qvs</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.qvs</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.qvs</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.qvs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Star * as joker for all fields</string>
			<key>match</key>
			<string>\*</string>
			<key>name</key>
			<string>keyword.operator.star.qvs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(and|or)\b)</string>
			<key>name</key>
			<string>keyword.operator.logical.qvs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bAS\b</string>
			<key>name</key>
			<string>keyword.other.alias.qvs</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LOAD and MAPPING LOAD keywords</string>
			<key>match</key>
			<string>(?i:\b(qualify|call|exit\s*script)\b)</string>
			<key>name</key>
			<string>keyword.other.load.qvs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(concatenate)(?=\s*\()\b)</string>
			<key>name</key>
			<string>keyword.other.load.qvs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(if|endif|end\s+if|elseif|else|then|not|or|and|sub|end\s+sub|switch|case|default|end\s+switch|for|to|step|exit\s+for|next|do|do\s+while|loop\s+until)\b</string>
			<key>name</key>
			<string>keyword.control.qvs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(applymap|if)(?=\s*\()</string>
			<key>name</key>
			<string>support.function.other.qvs</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.store.qvs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.qvs</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>STORE xxx INTO</string>
			<key>match</key>
			<string>(?i:^\s*(store)\s+\[*\w*\]*\s+(into))</string>
			<key>name</key>
			<string>meta.store.qvs</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.create.qvs</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.qvs</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>DROP statement</string>
			<key>match</key>
			<string>(?i:^\s*(drop)\s+(tables|table|fields|field))</string>
			<key>name</key>
			<string>meta.drop.qvs</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>aggregationFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i:\b(sum|max|maxstring|minstring|min|avg|concat|count|NumAvg|NumericCount|NumMax|NumMin|NumSum|Median|NullCount|NumCount|textcount|only)(?=\s*\())</string>
					

					<key>name</key>
					<string>support.function.aggregate.qvs</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.source.qvs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.qvs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.qvs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:^rem\b)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.qvs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>name</key>
					<string>comment.block.qvs</string>
				</dict>
			</array>
		</dict>
		<key>counterFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(recno|rowno|iterno|autonumber|autonumberhash128|autonumberhash256|fieldvaluecount)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>dateTimeFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Functions that take a date as input</string>
					<key>match</key>
					<string>(?i)\b(second|minute|hour|day|dayname|daynumberofquarter|daynumberofyear|weekday|week|WeekName|weekyear|month|MonthName|MonthsName|year|YearName|QuarterName)(?=\s*\()</string>
					

					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(now|today|localtime|makedate|makeweekdate|maketime|converttolocaltime)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(yeartodate|setdateyear|setdateyearmonth|yearstart|yearend|inyear|inyeartodate|inquarter|inquartertodate|inday|indaytotime)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(addyears|addmonths|daystart|dayend|monthstart|MonthsStart|monthend|MonthsEnd|inmonth|inmonthtodate|inmonths|inmonthstodate|inweek|inweektodate|inlunarweek|inlunarweektodate|LastWorkDate|NetWorkDays|LunarWeekEnd|LunarWeekName|LunarWeekStart|QuarterEnd|QuarterStart|WeekEnd|WeekStart)(?=\s*\()</string>

					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>no imput functions</string>
					<key>match</key>
					<string>(?i)\b(timezone|gmt|utc|daylightsaving)(?=\s*\(\))</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(date|date#|time|time#|timestamp|timestamp#)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>colorFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Color functions</string>
					<key>match</key>
					<string>(?i)\b(argb|color|colormaphue|colormapjet|colormix1|colormix2|white|black|red|green|blue|brown|cyan|darkgray|LightBlue|LightCyan|LightGray|LightGreen|LightMagenta|LightRed|Magenta|QlikTechBlue|QlikTechGray|rgb|SysColor|yellow)(?=\s*\()</string>
					

					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>fieldNames</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.qvs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>definition.punctuation.string.end.qvs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.qvs</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.qvs</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>definition.punctuation.string.end.qvs</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>interRecordFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(exists|fieldindex|fieldvalue|peek|previous|lookup|FieldName|FieldNumber|TableName|TableNumber|NoOfFields|NoOfReports|NoOfRows|NoOfTables)(?=\s*\()</string>
					

					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>logicalFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(isnull|isnum|IsText|true|false|null)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>macros</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.qvs</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Variables like $PARAM1, $TM_SELECTION...</string>
					<key>match</key>
					<string>\$\(([A-Za-z][A-Za-z0-9_]+)\)</string>
					<key>name</key>
					<string>keyword.qvs</string>
				</dict>
			</array>
		</dict>
		<key>numerics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([1-9]+[0-9]*|0)</string>
					<key>name</key>
					<string>constant.numeric.integer.decimal.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(num|num#|money|money#|dual|ceil|floor|round|even|odd|log|log10|mode|pow|rand|sqr|sqrt|pi)(?=\s*\()</string>

					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>rangeFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(RangeAvg|RangeCorrel|RangeCount|RangeFractile|RangeIRR|RangeKurtosis|RangeMax|RangeMaxString|RangeMin|RangeMinString|RangeMissingCount|RangeMode|RangeNPV|RangeNullCount|RangeNumericCount|RangeOnly|RangeSkew|RangeStdev|RangeSum|RangeTextCount|RangeXIRR|RangeXNPV)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>scriptStatements</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>LOAD and MAPPING LOAD keywords</string>
					<key>match</key>
					<string>(?i:\b(join|left\s+join|right\s+join|inner\s+join|outer\s+join|left\s+keep|right\s+keep|inner\s+keep|mapping\s+load|info\s+load|bundle\s+info\s+load|load\s+distinct|load|direct\s+query|dimension|measure|detail|native|sql\s+select|inline|resident|autogenerate|from|where|while|group\sby|order\sby|asc|desc)\b)</string>
					<key>name</key>
					<string>keyword.other.load.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(crosstable)(?=\s*\()</string>
					<key>name</key>
					<string>keyword.other.load.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\b(add|alias|binary|buffer|bundle|directory|concatenate|noconcatenate|intervalmatch|trace|unqualify|qualify|include)\b)</string>
					<key>name</key>
					<string>keyword.other.source.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\b(odbc|connect\sto)\b)</string>
					<key>name</key>
					<string>keyword.other.source.qvs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:\b(set|let)\b)</string>
					<key>name</key>
					<string>keyword.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>stringFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(text|len|trim|ltrim|rtrim|subfield|left|right|replace|keepchar|purgechar|capitalize|chr|findoneof|index|upper|lower|midMapSubString|substringcount|TextBetween)(?=\s*\()</string>
					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
		<key>systemFunctions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b(filesize|FileBaseName|FileDir|FileTime|FileExtension|FileName|FilePath|filesize|documentname|DocumentPath|DocumentTitle|attribute|author|computername|GetExtendedProperty|GetFolderPath|GetObjectField|GetRegistryString|OSUser|QlikViewVersion|QvdCreateTime|QvdFieldName|QvdNoOfFields|QvdNoOfRecords|QvdTableName|QVUser|ReloadTime)(?=\s*\()</string>	

					<key>name</key>
					<string>support.function.other.qvs</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.qvs</string>
	<key>uuid</key>
	<string>76c5d355-f146-4396-8714-8a4b1e687fc2</string>
</dict>
</plist>
